---
$:
  preprocess: []
  npm:
    scripts: []
  emit:
    pattern:
      - /.+\.js$/i
    ignore:
      - /^(.*\/)?bin(\/?$)?/i
      - /^(.*\/)?node_modules(\/?$)?/i
  test:
    mocha:
      options:
        ui: 'bdd'
        reporter: 'spec'
    pattern:
      - /.+\.spec\.js$/i
    ignore: ~ 
  e2e:
    pattern:
      - /.+\.e2e\.js$/i
      # - debug.e2e.js
      # - changeWidgetUS.e2e.js
    ignore: []
    browsers: 
      - puppeteer
    wait:
      interval: 500
      timeout: 60000
      uri:
        - 'http://localhost/~admin/wordpress_4.8.2/wp-admin/'                                             

test-suite:
  root: 'tests'
  dependencies:
    chance: 'latest'  
