language: php
sudo: required
node_js:
  - 7
cache:
  edge: true
  directories:
    - $HOME/.composer/cache
    - $(npm root -g)
    - node_modules
    - $(npm config get prefix)/bin
branches:
  only:
    - master
    - dev
    - stage
    - test
before_install:
  - sudo rm -rf ~/.nvm
  - 'curl -sL "https://deb.nodesource.com/setup_${NODE_RELEASE}" | sudo -E bash -'
  - sudo apt-get install -y nodejs
  - cp bin/test/package.json .
after_success:
  - npm run coverage
after_script:
  - npm run remove-coverage
dist: trusty
group: edge
php:
  - 5.6
  - 7.1
install:
  - composer install
  - npm install
script:
  - composer test
  - npm test
env:
  global:
    - NODE_RELEASE=7.x
    - 'MAJOR_VERSIONS=master,stage'
    - E2E_TESTING=none
    - secure: 
        DTJvolhdOVZgGUr5eO7+GNVqVJsNJZPThFL4hGIUdSTegrQ9tfTRc/c600Udz7ydd9DDNVv90XSaKrFPXVfMJEwPtPz6ZLJyg1RQFArkielAVx2oeAomHnIua9wgw98JFFd9aHbbmWfHHbWyWlvsW/HFNXCmmTIftlQUzk1iZuB9M9TfZRUeuQ+kBdTENtvyI+uTaLsAOY/0ADMotTRtw0ACftPbdRlTB7A8uD77zUK7vYw/g8fIhMugpbWy8aBfS+zQDhnwKnqJqJgqeAHvEAej2AQ9RE1pe4Bb1SmE8v81b8oqx5FXXx0kJ2pr2PyreRaFikT253VIAFhxTkQOocbYvGVjxKUjNVrQLWklcvwN8m7HTY6ch0q4YZzNW1bpVBXGV8XwAtQFM9EA81hJ5PrMRDNDLzFhKtbhSSlTrdiVTp20UFZX5FMU+GnLbeGzXWFmw9J0v8YTdUOhXt9wXwPlhrdJe/XzJPHPNQYL+gf4r5/GX4CPd7lphrlHLOXo+suPofkKtX9jpGxas5612/VH5fzp1UMSNPPann1JtmsiQAVgS8pzaSv1QDu1FPDfdCYwICVA5o85Fm3lDaVsdzZIOF+DzwrNopy+0Amky3MML6psUwPCY/2kCfPQtZb1TopCOajue8KSHP7EC/rxLmQ7wLN55UwKCO34+4MJDP0=
    - secure: 
        qHjWd9bIUEFg65gt5HTAwv6KmyrkvCudzIE7HABWduJL4ac+K+w4XQ3atiUPVMWcPNKDKimUKJiQVwZx+XjNkAV/ULrTkHZOzytnzLO11duMyh0NA7UzDwrab8krkHF6L0+XvCe2Db8PMWh2lb+6hnQoc7+SaWe1oCxuenzJ3nsqk3LckIEanWo3iZzRWewmi5QwOWGtd3izAgNxFRG5hF+H6Ht9RhRsL/3y75DCnETRPunysczYiXjMionqXpsaEUAJd97b/Y0yInabkbjN44MsJXlRxaRghVhBbKqbLd9jQPXIs+68vshXI3ZcyW99ZJz59WKVnRpBQb9rKLQOCvs2hPkpmT60iGumjWdH1QbHa1py0QV/7rMdtnp5NsVneDIl9lNKlcRpJxI/BrW/C7fXdg6a2/TbHaLSDnLOCCOCT3HGul/8NrkyxpOATuil3MKP2WRUxbwY5i5cuB9mPdRLh3igDjZWs7VY2QEdMRbQdCezgSNE/aTwPjzEz0K24PdlfO8tSaX73rnCfRNHvW5xc8dnmme7jicGIV2e5hZW9JNM9idzD6Xt4c1X5J+usUYcDFVlxF/l0RLTGPWYdrz4dL3NuE/V0QFzdqVVt5Y4xRe343ATXZjhQ5aYq8/aYOfe8He5einavrCUTAEENrwm3dO5cyPpXhzFYVHICZU=
    - secure: 
        vRexPhah6pJnTuClSlekDeoUdaJGsmqGvVki98BV7x2B3KDLG3TfRQ/OXgdCEH/3ic2/NV3bkXn8npEKU4y0IVuu5MWLfC/E9iUWiLSOAqeuv7kTLt2sQAkfoSOkb3H5SYf7GUaBTS/GR5VPyInhqHMldGFUSGzv/dlykrQo3/KuJs1A5lSvNtsMEmX692b/GB7AOgvDcGipY7iS7WfIfkzYZAyEWIfTPbgv04AG6iIyI/v6A+Mt6qpH3j4ptX6p0/pQG/foKwvtI7F9TzuJZZAf0NdtCC7PompsPiEqgCJ8opFBhLQjUm1zzPhtRK1hrhTBuotFR7xxf2JVZOeLxYbwAMCSbENHszl0gYt/ACfaqm59zs0bvaw6oX1fQ1+uda2TSg4iuNc2u0QAD/bmaiD4hK3gUVtk515AA1j2umiVcVE9A0mKRNc4VnLJrg7Im4pyfnzhmoZhq7+8n/ND7bPkENGnXptE2j5BcghcBNg7n97RGhuudMsJoSwxn2A2lHzAALNVdRizrbgnqFrHw0rqql/wFE8gDCR5ePuNKcPJyYWIp14WhF2Z3zz68b+YvuDusX2O7nq0wUfR5NOWRl/0WSYwnhdWDdwv9c7P2ztMDu+5jTFbLI3SkuSv8HqcY9l0lNVCcdYkWo15Umm1ZTMfc3zXAJcfX01nhCJCgAg=
    - secure: 
        sT/GUNcxBG9PRCNSLfTIPWo8K4S/FQGozIWVIw7v4Lqj6wruENE7UuK+IIyfDqIN9y87CTcgZ9JdgZS5RBuGWSiht4Y/E0lYZyQjqiVj/UHWs6rQ9KWLmMSmAty2gDSdqkr0g8lSmAt2uQmuuq2bItFr92vBF2+tIg0/2ve5IVkF8cKdIjmg1rfgnPT4wWm31j0uKR8EvRqGPsySN81cw0CQoiRtNvaErzT/xZavT0QptNUJKG7aw/jcSBI4bZrxMU3quijMiMbMYK91tDc454ER5f5HfO5ZneUDcXsQ8sTO6ASxgVYKNS89wW5SXTEl1UwTf5f9nXB0KMDhTkX3gwVQk7+4RX1YJ010DRn0Owu9tIqJtoOR0Hc7joLZZ85NJfTDlfe+5AXKxtcdXVJ5JlGN4teLHY+9+4dHWVvLz+EcVBnrT6fId7Q03xuC6xL6YZIsEWFXqTtRWRitiBJyo6ZYTWtVjUtE9tBMAiAftdGxDfBbYe6/pR9TWcd4SYd61lDod5YcxNaPiigFbx9TpUj5pZtphiwyiYdg7kOZ0cJWEgAJVt+iFmYIxWLzxn7uUL/dOVzLMjB6LYL2xTFzobtElJULuzSXPTfDKZ8UosYR06qe2vbpM6iUVd9TrBVaGJ0LblgRS+xNN6hM2Mf05qkGM2A6piLm1vsVPDjfeSw=
    - secure: 
        DyP3FRJBKU+o7x3CRJjv10j4L5tA29lIjsvrexqBbVcVBZ3fwRBgzkY9g8pMwsSGIfScr4UfY3qjXO6Je+dYwRT+3AKN6FfA/yGfCOrtVkVURPgMzUKrl0NpAoq5C2oPipN3a8vt+rUoQEAw8RtiefZ2ioT6g8m5E2mgzlns4ORKZnUTNnm1zKsr9QHh2zYOeiymodqyRQ2zkB5m08CFlVQBFaqM1I8cNcTGefWLGGWqcFY77qFkxOnuW8X5wwHsD8JeG22nXnaffCZWPbJcBGv7GnU44ehyULy+C5/clMxiq3+fO0B0Fim7Rq2UjG8Zt3zq0CT+5OBNBN+VHXp9K2BTcz9WNgsBjvvzcbVe9Y8rH7/6qW4G9KWxHwwjFCzsj2+unqnpFQcspQXb5Igu70qTG0/2oDnCwqrnSgKw7CQvFm2xnJfoFJk00extnF7vwPj/IFg7Exv4WE6cB/sKGjHaO4Fc94HJn1zxGRZPi4gQy+NYeYGC9qkLTkzj7USKJMuFOMFpL1ld8Qjw+JSwrma9NVtJy21GtfXf7Sc3HIElJmIOm2YgxV3Cj/VSsneZhdWJoZIsBXs604sa5expFpOnp7RVAYIslWM4A+LqmeOWmBnkoh1voXz8pgg08uuyND5cK58Hsm/99TtBs8+7eeRqHHZ3rzu2c+aPL6TGlJk=
    - secure: 
        z0Z1gILGzNo0tbVLgNsPTd+acO+WhKqKb6sLLHlJrDxsJzSTZNidX6QvdlUadOPMg774FgSflFVs0Vy/dH6SUBt/6Um4iGDoIXOBCfPKgq+lk1LET1/kgi9bdA8drJD9sAcRo980OYQGfnmHu7bkwYO3iW2hwF2b0nDX/2yY8ocotpkhwj9fFrmL1gMNjwnn+42GD+GIcwMWJQFgWZTmT6gBtTTdJPnC06VunkLO5eFN2H+I/mf8R1Y+n3ts1hTK0v2S9YqWBmqHaiemj5ibFn0YU27qUF3ouB8Ze02vrnHK9cy8OiAyhc9yWlfwM7Gw6awLdN2RF6nUmmih/QyB9hBe0exMeOSMhMoiPJd0yhKtFV4rEqtSsqn7ec5qDIKgRk5qSzZrWgDw4GrgU8tmhPFFXWV/oKV83yknTgUcCJrj1RCxl4JhU8vcpFDRtXNvmvuYF30oAQPOVemZ5L5VTVYdkXwyNLMc/qS4gpiK4zVA0Xwh/n4tYNQxdyzJ2jrDLjQxuovmczYy6t2XsHMYs/yBwO/s5mcbeT4PpKwy45oOlQ9ilEj7FDa4q1DMENYAtSidFJnNi0Py+RieIul8AL8BGYYDDUJixzljy0evM9ErPlFHCEtFdczO5lLxiIjPqlub3glEsrWp/Xy/StmfVs7q8orL0+urZp7Wpi5OVkA=
    - secure: 
        wlGFwfhCdjLn7pc4t/4Pvhh/U8gDE+tJgztdDy9qnZ/ScBTAFCMLTYGNA4z3nYhsYrLlPOz1fPcHkpWLCb6CW8KeXj6GVwbMkTh/eXQ0CWKrtLLD7hqvKZp2mkvNXTi/dxwiqyoCMAL3gu3bUUeErmyEv2SWJ8UIxxt2u4AGWmDAES8sneUvgz7oF7R85Wx1R/wb6SoSz7A7dkHtSpW/7OmUy9o2gGwTZkCdOGqvoADIT2uGYvhLwF3UGn/yTwQ0qfB1YWajGaCtLo7sjdEqsHbbIVhk7Q+I75zz/0/pnIXszc8Al1dfXrSpha2yrEdTPdMZ0rXGXyStV8za6kCj/xgOzU1FsYUMdVMUaDC69wizwk4B0e7dyR7SK6yS5MCgri6LcpFkxzQh73lgzuMWDAbb5wZFPUTZpm//yYErZ93AMlzanhOAi0KLdH/VdDzeC4N69WG7jX3f+NSHDWtyGKDbIHDZ08/25Q3+CSeD3HFZa4lhUYiT4qdQKVVi4BFh1FtDNDofzdO/O7OpcCjBnu9IRcgSg/7kLIKXKocrC9doaRaZgRP4yjhpyi8QDwKcVTmsUB8mMxrNlC3DrZerQnGk36LC3KVZdDKyi2FoXrBTQrB+3t6mRyF1Kk5HhAYtl1UmePg6j+tieXvSy2ER2kTB5n3ONJRZQ//KzlCTJEA=
notifications:
  slack:
    - secure: 
        WTAhVQkRLevsF6aJhkji6gbQ7QiDBYKDmLI4kUV37j5TZCNq7rCY5BeDWo8Ezk5hmrWqmckaxgV3G3horGRDaYsIqbT7vhdL4P1FSKbJKDZQQDV86c5SLNjRX3a/W33HCZGiy/8cIn7vFh8BdPHgTgxHV1Ay8TpGDq6yIiUBdEFaD9Yxqr/TVffHPn5C/NOoAC8o3JNRCmfiRX5ql7HoekS5Wlwpl1p5j6A+kNtnVbyEJYMj6xZfsz3tXhcC5T46QXEDfGP+wFYBtEAqGashlLC5tkKnZ3Q0T8ON240kr/X392kwPulMXTZbsqBRNX+Y57Z4K1kRzaaM2eG1mBBDxviZQ9KhObzGyRU6Vrm/7waTelFw1EslOpQxEQZKVPK+hu8c3TboVEPIGx8cDQXXWLMHo2PJtf4MUv/7Ke92I6mH9jVXii4mEfzH8tRRaGTFj/mU3W4yiubhWNGE2eZ1Q9KY00EBZGPs8q7sMBoNAy3NPgNMhZNXupDdC0HADIZ1FbbupPrvCk8Olmt+ZadwM2RvVqrbeD0mNt6INel9ttiQ0Uezt4UyHgWw/GekXE+oZaB53TrBWueOUze+MzVYNiVgw2j1ZHpHvL2j76o925lz9cX/cAOOizMHI/BSpC4tDwQQFMdLRbHhR0X4IwMehH02igEeFFrqhbVc2e8n0FI=
