language: node_js
sudo: required
node_js:
  - '4.3'
  - '6.6'
cache:
  edge: true
  directories:
    - $(npm root -g)
    - node_modules
    - deep_modules
    - $(npm config get prefix)/bin
branches:
  only:
    - master
    - dev
    - stage
    - test
before_install:
  - cp bin/test/package.json .
after_success:
  - npm run coverage
after_script:
  - npm run remove-coverage
env:
  matrix:
    - TEST_SUITE=backend
    - TEST_SUITE=frontend
  global:
    - 'MAJOR_VERSIONS=master,stage'
    - DEEP_NO_INTERACTION=1
    - E2E_TESTING=none
    - secure: 
        DTJvolhdOVZgGUr5eO7+GNVqVJsNJZPThFL4hGIUdSTegrQ9tfTRc/c600Udz7ydd9DDNVv90XSaKrFPXVfMJEwPtPz6ZLJyg1RQFArkielAVx2oeAomHnIua9wgw98JFFd9aHbbmWfHHbWyWlvsW/HFNXCmmTIftlQUzk1iZuB9M9TfZRUeuQ+kBdTENtvyI+uTaLsAOY/0ADMotTRtw0ACftPbdRlTB7A8uD77zUK7vYw/g8fIhMugpbWy8aBfS+zQDhnwKnqJqJgqeAHvEAej2AQ9RE1pe4Bb1SmE8v81b8oqx5FXXx0kJ2pr2PyreRaFikT253VIAFhxTkQOocbYvGVjxKUjNVrQLWklcvwN8m7HTY6ch0q4YZzNW1bpVBXGV8XwAtQFM9EA81hJ5PrMRDNDLzFhKtbhSSlTrdiVTp20UFZX5FMU+GnLbeGzXWFmw9J0v8YTdUOhXt9wXwPlhrdJe/XzJPHPNQYL+gf4r5/GX4CPd7lphrlHLOXo+suPofkKtX9jpGxas5612/VH5fzp1UMSNPPann1JtmsiQAVgS8pzaSv1QDu1FPDfdCYwICVA5o85Fm3lDaVsdzZIOF+DzwrNopy+0Amky3MML6psUwPCY/2kCfPQtZb1TopCOajue8KSHP7EC/rxLmQ7wLN55UwKCO34+4MJDP0=
    - secure: 
        qHjWd9bIUEFg65gt5HTAwv6KmyrkvCudzIE7HABWduJL4ac+K+w4XQ3atiUPVMWcPNKDKimUKJiQVwZx+XjNkAV/ULrTkHZOzytnzLO11duMyh0NA7UzDwrab8krkHF6L0+XvCe2Db8PMWh2lb+6hnQoc7+SaWe1oCxuenzJ3nsqk3LckIEanWo3iZzRWewmi5QwOWGtd3izAgNxFRG5hF+H6Ht9RhRsL/3y75DCnETRPunysczYiXjMionqXpsaEUAJd97b/Y0yInabkbjN44MsJXlRxaRghVhBbKqbLd9jQPXIs+68vshXI3ZcyW99ZJz59WKVnRpBQb9rKLQOCvs2hPkpmT60iGumjWdH1QbHa1py0QV/7rMdtnp5NsVneDIl9lNKlcRpJxI/BrW/C7fXdg6a2/TbHaLSDnLOCCOCT3HGul/8NrkyxpOATuil3MKP2WRUxbwY5i5cuB9mPdRLh3igDjZWs7VY2QEdMRbQdCezgSNE/aTwPjzEz0K24PdlfO8tSaX73rnCfRNHvW5xc8dnmme7jicGIV2e5hZW9JNM9idzD6Xt4c1X5J+usUYcDFVlxF/l0RLTGPWYdrz4dL3NuE/V0QFzdqVVt5Y4xRe343ATXZjhQ5aYq8/aYOfe8He5einavrCUTAEENrwm3dO5cyPpXhzFYVHICZU=
    - secure: 
        LSlYQujViMHDN1jEw0T1KHQFZszZj8szR7v//cEAi4E2gpzyaxMzg4lNLN2ss2Z08wGWn7zvavET/mFXfLk+o02xFLda8iAyj+Rl3tejkVGNlYWyhmtViWhUmx11gE+TcOMCahLH2noTkFQKX4B7hRToFM/7r66GQ5ooGGUTCu1u8qklZsYnm878+hzlSSF0ivELLkHsQhpW7WbowNTojzA9k4oAxTZGxvViarowvGlgUwnp09JsFdlcXeGQCDARLS3xZV+KPWdvR6pKvOmdeHrkpftSIW1NcaTWV6r/RR+AqhZtvEARTJKjlMB12J1LJk2jiqBsJ/nY6NZWsYg34/aCS9SCV2WIxiqIccxfIXCzMVb+8Ma5fDgj+KLiuMKZVrfzq3uGKMjVoqhtQ9Eh1S0V3ZYbjy0p4zhq+31QWQMv5wal/qEkZBUI/VejcVUtiEVeZGehn1kHm+fxzJJUBJg/xu7WsNhcwjyyX+R3SVHkPG4pCfPs7164TW0pyUNHIbdWHxgJBqrM2jllrs6DrEfoa1bIb4Xan1ZUxpYrLDfN6LSraOo/xl/U4hghAXYWkZUrKv7enpiN39X15YU4D3VpAAQoxbWJ5UxToiyZCIDgLOusHTXnPcRsc+TfBsYQr6pyfENaR2vWHAC2au2REztG+yEZeIYzz0a1Vl64AyU=
    - secure: 
        tYwZeZ3+Mrteq5Q+4tKHGCfv9DyE7cZ7f+FLzxH1mrChWiRV6O4LNL/ZX2ja3rSEVU7xtd2GOeNha06/xqA8ziy/4nRI6elo06OIYO1awxJ/9ZxM3Obk2HYFCsKjUZo3xI899VRUSopN7MEDQU1FV2WslalMEBEA6mPetrLPIyYWnHl+fTbCfnl4Bg3b6jsxdjMBQGIMgiUDPdmLo3AHJ+paJjTzTAJKuHTYVlzQ3qHF2jFQyG12EVTJ4nek+69kQz3IbZlco6ww0TACPlJ2o66GfZNyvIkMaO1i15cKrDG1j/MrwzOq3zP+Ipa+Ns3XVa4fuIILMFFgRG0q5TzL75iDyzJbiZNOh1yjaRlFdGUkTL9apNPq1zzn751JtBeq3WibE3FeeMH6gRxcY4zcJI0fKEdjtE3IuL2inSFKIUgJhnabSUVyhuCrFv6+T3to5i0ocMLN9aM6XZB/eTlxJgZgFS9I47zQ7VVhwDc3SWul7m6L4SoOeP3f8XfwcRJksvAHprstsnAh/sFp+GIv3nQ0n8eZ8BSy3arZQ/uoIFYV6klAGjaUwqEByo0kYm7dlJ52KEPCH0F2QmoaltbwuR4owHiTM87makkf6yZXV8ysYjuEbpNYE6pxZ7BXEMnKWl99AWUw0pSSB1wZNOZqFQyb5/AKasL94g4lmITKC4Y=
notifications:
  slack:
    secure: 
      WTAhVQkRLevsF6aJhkji6gbQ7QiDBYKDmLI4kUV37j5TZCNq7rCY5BeDWo8Ezk5hmrWqmckaxgV3G3horGRDaYsIqbT7vhdL4P1FSKbJKDZQQDV86c5SLNjRX3a/W33HCZGiy/8cIn7vFh8BdPHgTgxHV1Ay8TpGDq6yIiUBdEFaD9Yxqr/TVffHPn5C/NOoAC8o3JNRCmfiRX5ql7HoekS5Wlwpl1p5j6A+kNtnVbyEJYMj6xZfsz3tXhcC5T46QXEDfGP+wFYBtEAqGashlLC5tkKnZ3Q0T8ON240kr/X392kwPulMXTZbsqBRNX+Y57Z4K1kRzaaM2eG1mBBDxviZQ9KhObzGyRU6Vrm/7waTelFw1EslOpQxEQZKVPK+hu8c3TboVEPIGx8cDQXXWLMHo2PJtf4MUv/7Ke92I6mH9jVXii4mEfzH8tRRaGTFj/mU3W4yiubhWNGE2eZ1Q9KY00EBZGPs8q7sMBoNAy3NPgNMhZNXupDdC0HADIZ1FbbupPrvCk8Olmt+ZadwM2RvVqrbeD0mNt6INel9ttiQ0Uezt4UyHgWw/GekXE+oZaB53TrBWueOUze+MzVYNiVgw2j1ZHpHvL2j76o925lz9cX/cAOOizMHI/BSpC4tDwQQFMdLRbHhR0X4IwMehH02igEeFFrqhbVc2e8n0FI=
