---
engines:
  duplication:
    config:
      languages:
        javascript:
          mass_threshold: 350
ratings:
  paths:
  - "**.inc"
  - "**.module"
  - "**.php"
  - '**.css'
  - '**.inc'
  - '**.js'
  - '**.jsx'
  - '**.es6'
  - '**.module'
exclude_paths:
  - "**/bin"
  - "**/test"
  - "**/tests"
  - "**/tmp"
  - "**/vendor"
  - "**/.idea"
  - "**.spec.js"
  - "**.min.js"
  - "**.min.css"
  - "**/dist"
  - "**/node_modules"
  - "**/packages"
